### ISSUE TITLE
Train traffic light detector and classifier

### ISSUE THREAD

**Issue by ICGog** [erdos-project/pylot#11]
Pylot currently uses a traffic light detector and classifier that has been barely trained. We have to:

1. Train a traffic light detector. We could follow the steps from [here](https://becominghuman.ai/traffic-light-detection-tensorflow-api-c75fdbadac62) and [here](https://github.com/coldKnight/TrafficLight_Detection-TensorFlowAPI).
2. Ensure [https://github.com/erdos-project/pylot/blob/master/pylot/perception/detection/traffic_light_det_operator.py](https://github.com/erdos-project/pylot/blob/master/pylot/perception/detection/traffic_light_det_operator.py) uses your new model, and test how well it works by running ```python pylot.py --flagfiles=configs/traffic_light.conf```.

**Comment by sukritkalra** [comment]
- [ ] Add 3D bounding boxes for traffic lights in all the towns.
- [ ] Fix the x coordinates of middle traffic lights in Town05
- [ ] Integrate the bounding boxes of the traffic lights in world coordinates with the 3D to 2D conversion in `pylot/simulation/utils.py`

- [ ]
