### ISSUE TITLE
Issue with running docker container

### ISSUE THREAD

**Issue by wuxiaohua1011** [erdos-project/pylot#131]
Hi 
After talking with @pschafhalter , I tried to follow the Deploy using Docker tutorial. I encountered some hiccup and eventually am stucked on an error. 

The small hiccups are as follows, maybe it can help improve documentation:
- The command listed on the instruction `ssh -p 20022 -X erdos@localhost /bin/bash` will cause my command line to just hang there, therefore I just did `ssh -p 20022 -X erdos@localhost` and then when I am in the server, I manually execute `/bin/bash`, does this change affect anything?

- Also, it seems like PyGame is not installed by default in this docker image, I manually installed it using `pip3 install pygame`. 

----------------------------------------------------------------------------------------------------------------------------------------------------------------------
The error is described below: 
The error log is attached [here](https://gist.github.com/wuxiaohua1011/605d9681a81a7f1933808b5cc2225bbc)

Have you guys happened to encounter this? It seems like my GPU has ran its ram? From the `nvidia-smi` command, it seems like python is taking most from it? But I am not running any other program besides this one. 

My system specification are as follows:
OS: Ubuntu 18.04
Graphics Driver: NVIDIA-SMI 450.36.06    Driver Version: 450.36.06    CUDA Version: 11.0 
GPU: Nvidia RTX 2070 Super, 8GB memory

Here's the output from `nvidia-smi`
![Screenshot from 2020-07-18 22-14-57](https://user-images.githubusercontent.com/17909837/87867658-402ef600-c944-11ea-80cd-82240a96c3fe.png)

Here's screenshot of the the window for confirming Xauth is setted up correctly, carla server is running, and the terminal for running `python3 pylot.py --flagfile=configs/detection.conf --visualize_detected_obstacles`. 
![Screenshot from 2020-07-18 22-06-56](https://user-images.githubusercontent.com/17909837/87867703-9f8d0600-c944-11ea-9096-a5ddec3575f8.png)

Please let me know if any other info would be necessary. 

Thank you!

**Comment by wuxiaohua1011** [comment]
yeah, and i am pretty sure that it is the it is the `frenet_optimal_trajectory_planner/FrenetOptimalTrajectory` that is acting weird. 

Here's my GPU usage before running `python3 pylot.py --flagfile=configs/detection.conf --visualize_detected_obstacles`
![Screenshot from 2020-07-18 22-36-06](https://user-images.githubusercontent.com/17909837/87868062-6bffab00-c947-11ea-81d1-dc5a6181a182.png)

When I execute  `python3 pylot.py --flagfile=configs/detection.conf --visualize_detected_obstacles`, the program froze for a second with this error message
![Screenshot from 2020-07-18 22-36-54](https://user-images.githubusercontent.com/17909837/87868070-7de14e00-c947-11ea-9f02-c9a38c484dc4.png)

Then it went to on to complain about `trying to create rpc server for traffic manager; but the system failed to create because of bind error.`
![Screenshot from 2020-07-18 22-37-08](https://user-images.githubusercontent.com/17909837/87868081-95b8d200-c947-11ea-95e2-87c748bac547.png)

And somehow my GPU usage is ramped up to full
![Screenshot from 2020-07-18 22-37-24](https://user-images.githubusercontent.com/17909837/87868087-9f423a00-c947-11ea-9f1e-c228c75dbdd8.png)

**Comment by pschafhalter** [comment]
To fix the "Attempted to construct callback over more than 15 read streams bug", try the following:
1. Go to the ERDOS folder.
2. Find and replace 15 with 16 in `build.rs`.
3. Run `python python/setup.py install --user` to rebuild ERDOS.

I think you can fix the other errors with the following:
1. SSH into the docker container.
2. Run `/bin/bash`
3. `cd` into the Pylot directory.
4. Run `export PYLOT_HOME=$(pwd)`

Thanks for reporting These are issues we're aware of and are planning to fix before our upcoming release which should be more stable (sometime next week). CC @ICGog because I ran into these too when testing out the docker container last week.

**Comment by wuxiaohua1011** [comment]
hmm, Did you do anything else? 

i tried to replace 15 with 16 in `build.rs`. There are two places where the number 15 appears, one under the `make_add_watermark_callback` function, the other under the `make_callback_builder` function. 

I tried changing 15 -> 16 for both of them, and then for one of them respectively. They all resulted in different kinds of build errors. 

This is the error for changing 15 -> 16 for both of them
![Screenshot from 2020-07-19 17-29-40](https://user-images.githubusercontent.com/17909837/87889239-73759180-c9e5-11ea-90bc-9e994612710f.png)


This is the error for changing 15 -> 16 for watermark function. 
![Screenshot from 2020-07-19 17-31-39](https://user-images.githubusercontent.com/17909837/87889296-c0596800-c9e5-11ea-9577-044ba865165b.png)


And here's the error for changing 15 -> 16 for  `make_callback_builder`
![Screenshot from 2020-07-19 17-32-59](https://user-images.githubusercontent.com/17909837/87889334-e979f880-c9e5-11ea-9b3c-55703f805704.png)

**Comment by pschafhalter** [comment]
This should be fixed once erdos-project/erdos#132 is merged. In the meantime, you can add `16: "Sixteen"` to the `num_to_str` dictionary in `scripts/make_callback_builder.py`.

**Comment by ICGog** [comment]
Thanks for opening the issue. We've added a dependency on pygame, and merged in Peter's fix. Can you please try to:
pull erdos in the container: `cd ~/workspace/erdos ; git pull ; python3 python/setup.py install --user` ?

**Comment by wuxiaohua1011** [comment]
The build of ERDOS is successful

however, the command `python3 pylot.py --flagfile=configs/detection.conf --visualize_detected_obstacles` still errored out at loading the `build/libFrenetOptimalTrajectory.so`, here's the [gist](https://gist.github.com/wuxiaohua1011/49f23e4a719f6a974eb8d43c1c489578) for the error log.  
It seems to be complaining about 
`OSError: build/libFrenetOptimalTrajectory.so: cannot open shared object file: No such file or directory`

This file does exist in `~/workspace/pylot/dependencies/frenet_optimal_trajectory_planner/build` but it seems like the name has been referenced wrong in `frenet_optimal_trajectory_planner/FrenetOptimalTrajectory/fot_wrapper.py`


Some special notes: 
1. I had to install pygame manually,  I did that using the command `pip3 install pygame`
2. for adding public keys to access remote servers, the listed instruction in the readme is slightly off, shouldn't it be `pylot:DIRECTORY` instead of `pylot_new:DIRECTORY`
```
# readme
nvidia-docker cp ~/.ssh/id_rsa.pub pylot_new:/home/erdos/.ssh/authorized_keys
nvidia-docker exec -i -t pylot_new sudo chown erdos /home/erdos/.ssh/authorized_keys

# should be
sudo nvidia-docker cp ~/.ssh/id_rsa.pub pylot:/home/erdos/.ssh/authorized_keys
sudo nvidia-docker exec -i -t pylot sudo chown erdos /home/erdos/.ssh/authorized_keys
```

**Comment by ICGog** [comment]
Can you check if you have the PYLOT_HOME environment set to the pylot directory in your container? That should be enough for Pylot to find the Frenet file.

Another option is to `git pull` Pylot, which now shouldn't import the Frenet planner by default.

**Comment by pschafhalter** [comment]
I had to restart everything when this happened. This is the command I used:

`ps -ef | grep 'pylot' | grep -v grep | awk '{print $2}' | xargs -r kill -9`

**Comment by ICGog** [comment]
We've pushed out the ERDOS and Pylot 0.3. Can you please try again our docker image? Let us know if you run into any issues.

**Comment by wuxiaohua1011** [comment]
Hi, yes, it works perfectly. I just deleted the image, and then re-pulled the entire thing following the instruction provided in the readme, it worked without any hiccups. 

However, as #133 , it is also pretty laggy (but actually better than the manual installation)
