### ISSUE TITLE
Simulation is very laggy

### ISSUE THREAD

**Issue by wuxiaohua1011** [erdos-project/pylot#133]
Hi,
I am finally able to run PyLot. 

I found that the simulation is very laggy, especially when starting. And it freezes after a couple smooth frames

I've recorded a short clip to demonstrate the issue: 
[Manual Installation](https://youtu.be/O_NdJ0G6ouQ)
[Docker](https://youtu.be/GJyau_P-chU)

I am pretty sure that I am using my GPU
![Screenshot from 2020-07-22 19-17-35](https://user-images.githubusercontent.com/17909837/88246767-5ee90180-cc50-11ea-9cf7-571bba255241.png)

My system specification is as follows:
OS: Ubuntu 18.04
GPU: RTX 2070 Super 8GB memory
CPU: Ryzen 3700X

As you can see in the video, im not running any other processes besides this. It would be great if you could provide a video demo. 

Also I observe that there is this constant stream of error, that did not lead the program to crash, but might be alarming
![Screenshot from 2020-07-22 19-12-04](https://user-images.githubusercontent.com/17909837/88246776-66100f80-cc50-11ea-8ced-9be57cfd742c.png)

**Comment by ICGog** [comment]
Please let us know what configuration file you're using to run pylot.

**Comment by wuxiaohua1011** [comment]
I am running `configs/detection.conf`

**Comment by ICGog** [comment]
The simulation is lagging because the detection.config file create many agents in the simulation, and also because the default detection model is too big for you GPU. Please try to use a smaller model, and as well reduce the number of agents.

**Comment by Max-1925** [comment]
How big is the memory of your computer？

**Comment by pschafhalter** [comment]
Our setup has:
- 2× Xeon Gold 6226 CPUs
- 128GB of RAM 
- 2× Titan-RTX GPUs (24 GB of GPU memory each).

The exact resource requirements depend on the configuration of Pylot.
