### ISSUE TITLE
Bug in EfficientDetOperator

### ISSUE THREAD

**Issue by pschafhalter** [erdos-project/pylot#144]
The `EfficientDetOperator` expects to receive both `time_to_decision` and `detection_deadline` from the `TimeToDecisionOperator`, but the `TimeToDecisionOperator` only provides `time_to_decision`.

One potential workaround is to set `detection_deadline = ttd_msg.data` which fixes the exception. However, this solution doesn't work for dynamic configurations since the time allocated to detection is too large.

CC @sauravmittal

## Related Lines of Code

https://github.com/erdos-project/pylot/blob/793b0c21b0d21d4057626f67e9acfa2b127c111f/pylot/perception/detection/efficientdet_operator.py#L162

https://github.com/erdos-project/pylot/blob/08b8db469d2745a04b04fe81a94ed9262ea839b1/pylot/control/time_to_decision_operator.py#L18-L37

**Comment by ICGog** [comment]
I've pushed the workaround fix for this bug.
