### ISSUE TITLE
Bug in pylot.py

### ISSUE THREAD

**Issue by sauravmittal** [erdos-project/pylot#145]
__Reference before assignment__ error for `node_handle` in `pylot.py` on line 277.

https://github.com/erdos-project/pylot/blob/793b0c21b0d21d4057626f67e9acfa2b127c111f/pylot.py#L277

If the code gets an exception before the variable is assigned in the `try` block then the call to `shutdown_pylot` throws a `UnboundLocalError` reference before assignment error. So far, this bug has been observed when Pylot fails to find a graphics card.

https://github.com/erdos-project/pylot/blob/793b0c21b0d21d4057626f67e9acfa2b127c111f/pylot.py#L266-L278

This might need more specific error catching blocks so we only call `shutdown_pylot` with `node_handle` only when we have access to the variable and only when we need it. 

CC: @pschafhalter

**Comment by ICGog** [comment]
Thanks for the bug report. I've pushed a fix for it in f3bbaad.
