### ISSUE TITLE
xdg-user-dir: not found

### ISSUE THREAD

**Issue by zzzwww** [erdos-project/pylot#158]
Hello, thank you very much for the code.
However,  when I run **nvidia-docker exec -i -t pylot /home/erdos/workspace/pylot/scripts/run_simulator.sh**  I get an error. It seems that I can not start the CARLA.  I would appreciate it if you could help me@ICGog . 

> 4.24.3-0+++UE4+Release-4.24 518 0
> Disabling core dumps.
> sh: 1: xdg-user-dir: not found
> ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
> ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
> ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
> ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
> ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
> ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
> ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
> ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
> ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
> ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
> ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
> ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
> ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
> ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
>

**Comment by pschafhalter** [comment]
Hi, thank you for creating the issue. This looks like normal output when launching CARLA. Also, you shouldn't see a window pop up because we run CARLA in headless mode. Pylot should work fine as long as the CARLA process is running (you can check this using `top`).

Feel free to re-open if this doesn't solve your issue.
