### ISSUE TITLE
Readme instructions outdated?

### ISSUE THREAD

**Issue by OmarHedeya95** [erdos-project/pylot#162]
Hello everyone,
I am trying to get started but it seems to me that the instructions in the readme file are somehow outdated? For example running nvidia-docker seems to be deprecated and now one should use something like "docker run --gpus all ....". Now, for me as a beginner, it is getting quite difficult to run the simulator using nvidia-docker. I can run the "hello world" example using nvidia docker, but I do not know how to run the pylot using the new syntax and running the command 
`nvidia-docker run -itd --name pylot -p 20022:22 erdosproject/pylot /bin/bash`
ends up with 
"docker: Error response from daemon: Unknown runtime specified nvidia"

So would it be possible to tell me how to get started and maybe update the readme file? Thanks a lot!

**Comment by ICGog** [comment]
You can either downgrade to an older docker version, or you can run the container using `docker run --gpus all`. Please feel free to re-open the issue if this doesn't fix your problem.
