### ISSUE TITLE
X Error of failed request:  BadValue (integer parameter out of range for operation)

### ISSUE THREAD

**Issue by OmarHedeya95** [erdos-project/pylot#163]
Hey everyone,
This might be related to the previous issue so feel free to close whichever you find is less important. I tried to use the new syntax of docker instead nvidia-docker, however when following the first example that is supposed to produce detected objects, I end up with the above mentioned error. Here are the steps: 

1. `docker run --gpus all -itd --name pylot -p 20022:22 erdosproject/pylot /bin/bash`
2. `docker exec -i -t pylot /home/erdos/workspace/pylot/scripts/run_simulator.sh`
    1. Leads to 

    sh: 1: xdg-user-dir: not found
    ALSA lib confmisc.c:767:(parse_card) cannot find card '0'

    According to what I read this is not an issue

3. Then I follow the steps leading to visualize detected objects (the only difference is that I use docker directly instead of nvidia-docker since it is deprecated) but I get the following message, :

    erdos@75a2ddf2bdc5:~/workspace/pylot$ python3 [pylot.py](http://pylot.py/) --flagfile=configs/detection.conf --visualize_detected_obstacles
    I0306 17:18:32.899067 140158380492608 **init**.py:409] $HOME=/home/erdos
    I0306 17:18:32.899491 140158380492608 **init**.py:409] matplotlib data path /home/erdos/.local/lib/python3.6/site-packages/matplotlib/mpl-data
    I0306 17:18:32.904089 140158380492608 **init**.py:1156] loaded rc file /home/erdos/.local/lib/python3.6/site-packages/matplotlib/mpl-data/matplotlibrc
    I0306 17:18:32.906330 140158380492608 **init**.py:1879] matplotlib version 2.2.4
    I0306 17:18:32.906501 140158380492608 **init**.py:1880] interactive is False
    I0306 17:18:32.907129 140158380492608 **init**.py:1881] platform is linux

    .......

    pygame 2.0.0 (SDL 2.0.12, python 3.6.9)
    Hello from the pygame community. [https://www.pygame.org/contribute.html](https://www.pygame.org/contribute.html)
    X Error of failed request:  BadValue (integer parameter out of range for operation)
    Major opcode of failed request:  155 (GLX)
    Minor opcode of failed request:  3 (X_GLXCreateContext)
    Value in failed request:  0x0
    Serial number of failed request:  86
    Current serial number in output stream:  87

    Can someone please help me identify what could be wrong? Thank you!

    I am using Ubuntu 18.04

    Nvidia drivers: 450.102.04

    Cuda Version: 11.0

**Comment by ICGog** [comment]
Can you please refer to this issue: https://github.com/erdos-project/pylot/issues/152? Downgrading pygame to 1.9.6 should do it. Please run: `pip3 install pygame==1.9.6` in the container.

Feel free to re-open if this doesn't fix your issue.
