### ISSUE TITLE
AttributeError: 'Obstacle' object has no attribute 'bounding_box_2D'

### ISSUE THREAD

**Issue by OmarHedeya95** [erdos-project/pylot#164]
Hey,
I get the above error when running :
`python3 data_gatherer.py --flagfile=configs/data_gatherer.conf`
The code stills produce pictures though but I just wanted to make sure if this is something to worry just in case I might be doing something wrong. Thank you

**Comment by ICGog** [comment]
Thanks for finding this bug. I've pushed a fix (see https://github.com/erdos-project/pylot/pull/165) to the master branch. Please pull the master branch in your container to get this fix.
