### ISSUE TITLE
error on runnuing pylot.py

### ISSUE THREAD

**Issue by hadeeressamanwer** [erdos-project/pylot#184]
![Screenshot from 2021-04-19 03-41-31](https://user-images.githubusercontent.com/54284446/115170536-2ed86d00-a0c1-11eb-91e8-57a7745582c2.png)
can anyone help me please
when i try to run pylot.py these errors appear to me 
OSError: build/libFrenetOptimalTrajectory.so: cannot open shared object file: No such file or directory

OSError: /home/user/pylot//dependencies/frenet_optimal_trajectory_planner/build/libFrenetOptimalTrajectory.so: cannot open shared object file: No such file or directory

ERROR: CARLA version 784d9b9f is not supported; assuming this is version 0.9.10

RuntimeError: trying to create rpc server for traffic manager; but the system failed to create because of bind error.

![Screenshot from 2021-04-19 03-23-09](https://user-images.githubusercontent.com/54284446/115169544-99d47480-a0be-11eb-840d-6c7ab246a847.png)

**Comment by FitashUlHaq** [comment]
Advice from fellow user: use docker, it already handles all these errors

**Comment by ICGog** [comment]
As Fitash suggested, I advise you to use the Docker image we provide as it already has installed all the required dependencies.

It looks like there's a bunch of issues with your current instalattion:

1. Cuda doesn't find a device. You can check if your GPU is visible by running `nvidia-smi`.
2. The Frenet Optimal Trajectory planner is not installed. Have you executed `./install.sh`?
3. The port specified by carla_traffic_manager_port is already in use. Please try to use a different port.

**Comment by Chiakiaki** [comment]
Hi, I met the same issue. The reason is not setting PYLOT_HOME, as seen in the for_wrapper.py:

try:
    cdll = CDLL("build/libFrenetOptimalTrajectory.so")
except:
    cdll = CDLL("{}/dependencies/frenet_optimal_trajectory_planner/"
                "build/libFrenetOptimalTrajectory.so".format(
                    os.getenv("**PYLOT_HOME**")))
