### ISSUE TITLE
How does the planning operator work with the behavior planning state?

### ISSUE THREAD

**Issue by yanmiao2** [erdos-project/pylot#209]
Hi developers, I have a question about behavior planning and planner.

In my understanding of pylot, the behavior planner sends state info(E.g. `OVERTAKE`,  `LANE_CHANGE_LEFT`) to the planning operator and is stored ![Here](https://github.com/erdos-project/pylot/blob/fdba02482f7be134a106479c96ad43273f4235d3/pylot/planning/planning_operator.py#L157). However, that state variable only gets updated and never gets used in class `PlanningOperator`.  

Therefore, the trajectory generated by the planner never used that info from behavior planning, did I miss anything here?

**Comment by ICGog** [comment]
Your understanding is correct. The behavior planner is still under development, and thus is not plugged in the main branch or in the Docker container. The latest release of Pylot just follows waypoints when the waypoint planner is used (might get blocked behind stuck vehicles) or always tries to overtake stationary vehicles when the other planners are used (FOT, RRT*, Hybrid A*).
