### ISSUE TITLE
Carla Simulator fails to start in Docker 

### ISSUE THREAD

**Issue by JackWetherell** [erdos-project/pylot#210]
Following the docker installation instructions:
```
docker pull erdosproject/pylot
nvidia-docker run -itd --name pylot -p 20022:22 erdosproject/pylot /bin/bash
nvidia-docker exec -i -t pylot /home/erdos/workspace/pylot/scripts/run_simulator.sh
```
gives the following output:
```
4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
sh: 1: xdg-user-dir: not found
```
**And then the simulator does not seem to start, the terminal returns control to the user.**
Then when I try to run pylot, I get the expected error that Carla is not running:
```
# nvidia-docker exec -i -t pylot /bin/bash
erdos@40d58cdbed32:~/workspace/pylot$ cd workspace/pylot/
bash: cd: workspace/pylot/: No such file or directory
erdos@40d58cdbed32:~/workspace/pylot$ python3 pylot.py --flagfile=configs/detection.conf
Traceback (most recent call last):
  File "/home/erdos/workspace/pylot/pylot/simulation/utils.py", line 57, in get_world
    server_version = client.get_server_version()
RuntimeError: time-out of 5000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:2000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pylot.py", line 272, in <module>
    app.run(main)
  File "/home/erdos/.local/lib/python3.6/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/erdos/.local/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "pylot.py", line 255, in main
    FLAGS.simulator_timeout)
  File "/home/erdos/workspace/pylot/pylot/simulation/utils.py", line 65, in get_world
    "simulator: {}".format(r))
Exception: Received an error while connecting to the simulator: time-out of 5000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:2000
```
Docker versions:
```
docker 1:20.10.8-1
nvidia-docker 2.6.0-1
```

**Comment by ICGog** [comment]
Hi Jack,

Indeed, it looks like the simulator is not starting because: 1) run_similator.sh should not return, and 2) Pylot fails to connect to the simulator. I haven't seen this issue before, but can you please try to remove `-opengl` in the `run_simulator.sh` script? If this doesn't help, then can you please double check that your GPU is available inside the docker container by running `nvidia-smi`?

**Comment by JackWetherell** [comment]
HI @ICGog. Thank you for the response. I have discovered that the following seems to work for me:

In terminal 1:
`nvidia-docker run -itd --name pylot -p 20022:22 --privileged --rm --gpus all -e DISPLAY= -e SDL_VIDEODRIVER=offscreen erdosproject/pylot /bin/bash`
`nvidia-docker exec -i -t pylot /home/erdos/workspace/pylot/scripts/run_simulator.sh`

In terminal 2:

`nvidia-docker cp ~/.ssh/id_rsa.pub pylot:/home/erdos/.ssh/authorized_keys`
`nvidia-docker exec -i -t pylot sudo chown erdos /home/erdos/.ssh/authorized_keys`
`nvidia-docker exec -i -t pylot sudo service ssh start`
`ssh -p 20022 -X erdos@localhost`
`cd /home/erdos/workspace/pylot/`
`python3 pylot.py --flagfile=configs/detection.conf --visualize_detected_obstacles`

And then I see the object detection window load.

However, when I run the demo:
`python3 pylot.py --flagfile=configs/demo.conf`

I get the error:
`FATAL Flags parsing error: flags visualize_prediction=True, execution_mode=simulation: --visualize_prediction can only be enabled when running atop the simulator`
Do you know how to fix this?
Many thanks.

**Comment by ICGog** [comment]
Hi @JackWetherell,

Thanks for catching this bug. This happens because the flag validator [here](https://github.com/erdos-project/pylot/blob/master/pylot/flags.py#L281) should check for equality with `"simulation"` not `"simulator"`. I have included a fix for this issue in PR https://github.com/erdos-project/pylot/pull/220.

Please pull the Pylot 0.3.3 Docker image (will be released today) to get this fix.

**Comment by luuqh** [comment]
Hi @ICGog,

I follow the instruction from the homepage: https://github.com/erdos-project/pylot/

After running the command
```
nvidia-docker exec -i -t pylot /home/erdos/workspace/pylot/scripts/run_simulator.sh
```
I ran into issue which says

```
4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
sh: 1: xdg-user-dir: not found
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
```

What does it mean and is there any hint for me to proceed?

FYI I pull the latest Docker version (as of today 6 Jan 2022). Docker versions:

```
NVIDIA Docker: 2.8.0
Docker: 20.10.12
```

Many thanks.

**Comment by panpan-77** [comment]
> Hi @ICGog,
> 
> I follow the instruction from the homepage: https://github.com/erdos-project/pylot/
> 
> After running the command
> 
> ```
> nvidia-docker exec -i -t pylot /home/erdos/workspace/pylot/scripts/run_simulator.sh
> ```
> 
> I ran into issue which says
> 
> ```
> 4.24.3-0+++UE4+Release-4.24 518 0
> Disabling core dumps.
> sh: 1: xdg-user-dir: not found
> ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
> ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
> ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
> ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
> ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
> ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
> ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
> ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
> ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
> ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
> ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
> ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
> ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
> ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
> ```
> 
> What does it mean and is there any hint for me to proceed?
> 
> FYI I pull the latest pylot version (as of today 6 Jan 2022). Docker versions:
> 
> ```
> NVIDIA Docker: 2.8.0
> Docker: 20.10.12
> ```
> 
> Many thanks.

Hello,
I have encountered the same situation. Have you solved this problem?
