### ISSUE TITLE
data_gatherer.py: what's the expecting output

### ISSUE THREAD

**Issue by estherxpr** [erdos-project/pylot#211]
Hi! We tried to run 
python3 data_gatherer.py --flagfile=configs/data_gatherer.conf

We ran it for a few minutes, and the only output is a very long (over 10,000 lines) data_gatherer.log. We are curious about two things:
1. what's the expecting output of this command? when will it terminate?
2. when we run data_gatherer.py, is it automatically doing the simulation as well?

Thanks!

**Comment by ICGog** [comment]
1. The data gatherer will create a `data` directory where it will log whatever is set in the configuration file you're passing to it. The default `configs/data_gathered.conf` logs images, segmented images, depth images, agent trajectories etc. The best way to decide what to log is by running `python3 data_gatherer.py --help` and inspecting the available flags.
2. You have to follow the same steps as when running Pylot, and manually run the simulator. If you're using the docker container you can run the simulator by executing ```nvidia-docker exec -i -t pylot /home/erdos/workspace/pylot/scripts/run_simulator.sh```

**Comment by estherxpr** [comment]
Thanks! I follow the steps, but it keeps complaining: FileNotFoundError: 
[Errno 2] No such file or directory: 'data/perfect-detector-92161.png'

I am using the docker container to run the data_gathered.conf. Did I miss anything?

**Comment by ICGog** [comment]
I think you might have to create the data directory manually (`cd $PYLOT_HOME; mkdir data`), because the script in the Docker image is a bit old.

**Comment by estherxpr** [comment]
This actually works. Thank you so much!
