### ISSUE TITLE
Lidar Logging Format

### ISSUE THREAD

**Issue by yanmiao2** [erdos-project/pylot#215]
Hi Developers,

I have enabled the `add_lidar_logging` function, but it seems to me that the output pointcloud file always have different output shape(E.g. (4017, 3), (4083, 3)). 

I'm wondering if there's some parameters in that Pylot provides so that we can specify all output shapes to specific dimension(E.g.(20, 20, -1))? That'll help us in doing some data processing.

Thanks

**Comment by ICGog** [comment]
A pointcloud reading includes a point for every ray that meets an obstacle within the LiDAR range. As a result, the number depends on how many obstacles are in the scene, and is expected to vary across readings.

We cannot guarantee a fixed number of points, but you can set an upper bound in your data processing script. However, you'll have to implement a policy to remove points that you deem to be non-essential.
