### ISSUE TITLE
Where to find pre-trained R2P2 model?

### ISSUE THREAD

**Issue by findaheng** [erdos-project/pylot#256]
I'm unable to use the R2P2PredictorOperator because the prediction flag for the model path `dependencies/models/prediction/r2p2/r2p2-model.pt` does not exist in this repository. In the prediction repo, I see the code to train a model, but I was hoping to use a pre-trained model. Could this `r2p2-model.pt` file be provided?

**Comment by ICGog** [comment]
We recommend using our Docker image where are all models are pre-packaged. However, if you don't want to use the image, then you have run `install.sh` to download and setup all the models.

If you already have a running setup and you just need the model, then run [this command from install.sh](https://github.com/erdos-project/pylot/blob/master/install.sh#L30) to download all our models. Next, you have to unzip them, and copy the r2p2 model to wherever you want store it.
