### ISSUE TITLE
how to get the conf file setting manual or documentation

### ISSUE THREAD

**Issue by aming439836** [erdos-project/pylot#284]
As you know , we need run the pylot by the flagfiles ? but I don't know how to  set and make a new flagfile , and can you show how to set the flagfile according to myself requirement ,and can you give me some manul or documentation which explain the setting in the flagfile ? 

thank you so much ,and looking forwards for your reply.

**Comment by aming439836** [comment]
for example :
![image](https://user-images.githubusercontent.com/50010679/200305182-033a8c5d-b27e-4a52-a955-0abf68f7da55.png)
how to get other flags setting in the above picture ?

**Comment by pschafhalter** [comment]
Hi,

Example flag files are available in the [`./configs`](https://github.com/erdos-project/pylot/tree/master/configs).

You can modify these, or use them to start your own!
