### ISSUE TITLE
Project running problem

### ISSUE THREAD

**Issue by zhouyu102030** [erdos-project/pylot#294]
I got the following error when executing this command. I would like to ask, should I run carla first before running this command?
![2023-05-12 01-38-49 的屏幕截图](https://github.com/erdos-project/pylot/assets/85484578/7d237bc5-8606-423d-b436-da53b140ba13)

**Comment by zhouyu102030** [comment]
In addition, I also want to ask if I want to run pylot, do I need to install Carla myself? Is there a requirement for Carla's version if necessary? Thank you for your answer!

**Comment by pschafhalter** [comment]
Hi,

CARLA should be installed in the Docker container, and you can launch CARLA after the container is running. This looks like an issue with NVIDIA Docker. It could be that you're using a newer GPU that doesn't support the CUDA version with which the Pylot container was built. You may need to run on an older GPU, or look into modifying the Pylot Dockerfile to use a newer CUDA version (although this might break some of the ML dependencies).
