### ISSUE TITLE
Meaning of the parameters

### ISSUE THREAD

**Issue by Morphlng** [erdos-project/pylot#295]
Hello! I noticed some sudden movement during control when applying the [person_avoidance_frenet](https://github.com/erdos-project/pylot/blob/master/configs/scenarios/person_avoidance_frenet.conf) configuration. 

The steering angle can become unexpectedly large, even during normal driving and not just when avoiding obstacles. I've found some definition of these flags here: [frenet_optimal_trajectory/flags.py](https://github.com/erdos-project/pylot/blob/master/pylot/planning/frenet_optimal_trajectory/flags.py). However, I've been unable to locate a comprehensive document that explains the purpose of each parameter in this configuration file. 

Could you please guide me to additional resources where I can gain a better understanding of these parameters? My goal is to enhance the car's driving experience and ensure smoother operation. Thank you!

**Comment by pschafhalter** [comment]
Hi, the following resources provide an explanation of the Frenet Optimal Trajectory algorithm and its parameters:
- [Optimal Trajectory Generation for Dynamic Street Scenarios in a Frenet Frame](https://www.researchgate.net/publication/224156269_Optimal_Trajectory_Generation_for_Dynamic_Street_Scenarios_in_a_Frenet_Frame)
- [§4.3 of Edward Fang's master's thesis](https://digitalassets.lib.berkeley.edu/techreports/ucb/incoming/EECS-2020-58.pdf)
