### ISSUE TITLE
Dynamic deadline

### ISSUE THREAD

**Issue by ahmedius2** [erdos-project/pylot#301]
Please let me know in which part of the code the dynamic deadlines are determined by the scheduler.

**Comment by pschafhalter** [comment]
https://github.com/erdos-project/pylot/blob/a71ae927328388dc44acc784662bf32a99f273f0/pylot/control/time_to_decision_operator.py

There are more complex implementations in some of the other branches, e.g. `deadlines-ttd`:
https://github.com/erdos-project/pylot/blob/deadlines-ttd/pylot/control/time_to_decision_operator.py

For more information on replicating the experiments from the [paper on dynamic deadlines](https://pschafhalter.com/data/papers/2022-eurosys-d3.pdf), see [erdos-project/erdos-experiments](https://github.com/erdos-project/erdos-experiments).
