### ISSUE TITLE
Improve DeepSORT Tracking

### ISSUE THREAD

**Issue by amandhar** [erdos-project/pylot#34]
Need to collect additional data with bounding boxes now that those are more accurate. Then should re-train the pedestrian feature extractor net and add to pylot.

**Comment by ICGog** [comment]
I've noticed that DeepSORT and SORT trackers do not maintain the label of tracked obstacles. I've patched the SORT repo, but I haven't figured out a way to do it in the DeepSORT repo. It would be nice at some point to update the DeepSORT repo to maintain labels, but it is low priority for now.

**Comment by ICGog** [comment]
I'm closing this issue because we've addressed these limitations.
