### ISSUE TITLE
Refactor Pylot

### ISSUE THREAD

**Issue by sukritkalra** [erdos-project/pylot#38]
- [x] Fix the weather presets. We don't need to pass arbitrary integers and can use strings with named presets now.
- [x] Fix the pylot versions of Location and Transform. We have multiple helper functions across the pipeline that could be refactored as methods inside these classes.
- [x] Consolidate the functions that reference `pylot.BoundingBox` inside the class.
- [x] Deprecate `to_pylot_transform` and `to_pylot_location`
- [x] Introduce a Vector3D class as a base class for Location and Orientation and then deprecate Orientation.
- [x] Move `*_to_unreal_transform` functions inside the Setup classes as static methods.
- [x] Create a new class for Rotation and deprecate forward_vector as an input to Transform. Retrieve it from the Rotation class.
- [x] Move flags to individual modules.
- [x] Deprecate `inverse_transform` and introduce functions that convert locations with respect to the transform.

**Comment by ICGog** [comment]
Closing this issue because all outstanding tasks have been solved.
