### ISSUE TITLE
Convert tracking output stream messages for prediction tasks

### ISSUE THREAD

**Issue by amandhar** [erdos-project/pylot#69]
The object tracker operator sends ObstaclesMessage objects on an output stream, as these messages contain bounding boxes that are read by the tracking evaluation operator. However, the prediction component requires past trajectory information from trackers, which should come in an ObstacleTrajectoriesMessage. 

To address this, write an operator that converts ObstaclesMessages to ObstacleTrajectoriesMessages.

**Comment by ICGog** [comment]
I've addressed this issue in this commit: https://github.com/erdos-project/pylot/commit/576ef59e07b8dfcca5d138558d4d2a25f5356e44
